plank:
  default_decoration_configs:
    '*':
      utility_images: # using the tag we identified above
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200520-e1124f454"
        initupload: "gcr.io/k8s-prow/initupload:v20200520-e1124f454"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200520-e1124f454"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200520-e1124f454"
      gcs_configuration:
        bucket: voyager-utils
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials # the secret we just made

periodics:
- interval: 10m
  name: echo-test
  decorate: true
  spec:
    containers:
    - image: alpine
      command: ["/bin/date"]
postsubmits:
  necobot/prow-test:
  - name: test-postsubmit
    decorate: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]
presubmits:
  necobot/prow-test:
  - name: test-presubmit
    decorate: true
    always_run: true
    skip_report: true
    spec:
      containers:
      - image: alpine
        command: ["/bin/printenv"]

tide:
  sync_period: 2m
  queries:
  - repos:
    -  necobot/prow-test
    labels:
    - lgtm
    - approved
    missingLabels:
    - do-not-merge
    - do-not-merge/blocked-paths
    - do-not-merge/hold
    - do-not-merge/invalid-owners-file
    - do-not-merge/work-in-progress
    - needs-rebase

